### ISSUE TITLE
S3 container sometimes doesn't resolve from PHP container

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-local-server#761]
Sometimes, whether from a brand-new stack or an existing stack, uploading images results in an error that boils down to the PHP container being unable to resolve the MinIO s3 emulation container.

Here's a brain dump of notes from a brief investigation into the problem. Note, sometimes the S3 container does resolve, but the Tachyon one doesn't. This has only occurred on one machine. A previous macBook does not exhibit the problem (but then my current one didn't used to either). It doesn't occur (for me) on Linux (Ubuntu 24.04).

- Found fatal error uploading an image as author
```log
qatest-php  | [07-Aug-2024 09:35:43 UTC] PHP Warning:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "ListObjectsV2" on "https://s3-qatest.altis.dev/s3-qatest/?list-type=2&delimiter=%2F&prefix=uploads%2F2024%2F08%2Fzed1-img_1777"; AWS HTTP error: cURL error 7: Failed to connect to s3-qatest.altis.dev port 443 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3-qatest.altis.dev/s3-qatest/?list-type=2&delimiter=%2F&prefix=uploads%2F2024%2F08%2Fzed1-img_1777'
qatest-php  |
qatest-php  | GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to s3-qatest.altis.dev port 443 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3-qatest.altis.dev/s3-qatest/?list-type=2&delimiter=%2F&prefix=uploads%2F2024%2F08%2Fzed1-img_1777 in /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:275
qatest-php  | Stack trace:
qatest-php  | #0 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(205): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
qatest-php  | #1 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(157): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
qatest-php  | #2 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(267): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlMultiHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
qatest-php  | #3 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(180): GuzzleHttp\Handler\CurlMultiHandler->processMessages()
qatest-php  | #4 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(206): GuzzleHttp\Handler\CurlMultiHandler->tick()
qatest-php  | #5 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
qatest-php  | #6 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
qatest-php  | #7 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
qatest-php  | #8 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
qatest-php  | #9 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
qatest-php  | #10 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
qatest-php  | #11 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
qatest-php  | #12 /usr/src/app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
qatest-php  | #13 /usr/src/app/vendor/aws/aws-sdk-php/src/ResultPaginator.php(138): Aws\AwsClient->execute(Object(Aws\Command))
qatest-php  | #14 /usr/src/app/vendor/aws/aws-sdk-php/src/functions.php(52): Aws\ResultPaginator->valid()
qatest-php  | #15 /usr/src/app/vendor/aws/aws-sdk-php/src/functions.php(69): Aws\map(Object(Aws\ResultPaginator), Object(Closure))
qatest-php  | #16 [internal function]: Aws\flatmap(Object(Aws\ResultPaginator), Object(Closure))
qatest-php  | #17 /usr/src/app/vendor/humanmade/s3-uploads/inc/class-stream-wrapper.php(695): Generator->valid()
qatest-php  | #18 [internal function]: S3_Uploads\Stream_Wrapper->dir_readdir()
qatest-php  | #19 /usr/src/app/vendor/humanmade/s3-uploads/inc/class-plugin.php(676): scandir('s3://s3-qatest/...')
qatest-php  | #20 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(324): S3_Uploads\Plugin->get_files_for_unique_filename_file_list(NULL, 's3://s3-qatest/...', 'zed1-img_1777.j...')
qatest-php  | #21 /usr/src/app/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
qatest-php  | #22 /usr/src/app/wordpress/wp-includes/functions.php(2667): apply_filters('pre_wp_unique_f...', NULL, 's3://s3-qatest/...', 'zed1-img_1777.j...')
qatest-php  | #23 /usr/src/app/wordpress/wp-admin/includes/file.php(984): wp_unique_filename('s3://s3-qatest/...', 'zed1-img_1777.j...', NULL)
qatest-php  | #24 /usr/src/app/wordpress/wp-admin/includes/file.php(1105): _wp_handle_upload(Array, Array, '2024-08-07 09:3...', 'wp_handle_uploa...')
qatest-php  | #25 /usr/src/app/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(1322): wp_handle_upload(Array, Array, '2024-08-07 09:3...')
qatest-php  | #26 /usr/src/app/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(269): WP_REST_Attachments_Controller->upload_from_file(Array, Array, '2024-08-07 09:3...')
qatest-php  | #27 /usr/src/app/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(158): WP_REST_Attachments_Controller->insert_attachment(Object(WP_REST_Request))
qatest-php  | #28 /usr/src/app/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Attachments_Controller->create_item(Object(WP_REST_Request))
qatest-php  | #29 /usr/src/app/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/media', Array, NULL)
qatest-php  | #30 /usr/src/app/wordpress/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
qatest-php  | #31 /usr/src/app/wordpress/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/wp/v2/media')
qatest-php  | #32 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
qatest-php  | #33 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(false, Array)
qatest-php  | #34 /usr/src/app/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
qatest-php  | #35 /usr/src/app/wordpress/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
qatest-php  | #36 /usr/src/app/wordpress/wp-includes/class-wp.php(813): WP->parse_request('')
qatest-php  | #37 /usr/src/app/wordpress/wp-includes/functions.php(1336): WP->main('')
qatest-php  | #38 /usr/src/app/wordpress/wp-blog-header.php(16): wp()
qatest-php  | #39 /usr/src/app/index.php(21): require('/usr/src/app/wo...')
qatest-php  | #40 {main}
qatest-php  |
qatest-php  | Next Aws\S3\Exception\S3Exception: Error executing "ListObjectsV2" on "https://s3-qatest.altis.dev/s3-qatest/?list-type=2&delimiter=%2F&prefix=uploads%2F2024%2F08%2Fzed1-img_1777"; AWS HTTP error: cURL error 7: Failed to connect to s3-qatest.altis.dev port 443 after 0 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3-qatest.altis.dev/s3-qatest/?list-type=2&delimiter=%2F&prefix=uploads%2F2024%2F08%2Fzed1-img_1777 in /usr/src/app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:196
qatest-php  | Stack trace:
qatest-php  | #0 /usr/src/app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\Psr7\Request), Object(Aws\Command), Array)
qatest-php  | #1 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(209): Aws\WrappedHttpHandler->Aws\{closure}(Array)
qatest-php  | #2 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(174): GuzzleHttp\Promise\Promise::callHandler(2, Array, NULL)
qatest-php  | #3 /usr/src/app/vendor/guzzlehttp/promises/src/RejectedPromise.php(49): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(Array)
qatest-php  | #4 /usr/src/app/vendor/guzzlehttp/promises/src/TaskQueue.php(52): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}()
qatest-php  | #5 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(167): GuzzleHttp\Promise\TaskQueue->run()
qatest-php  | #6 /usr/src/app/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(206): GuzzleHttp\Handler\CurlMultiHandler->tick()
qatest-php  | #7 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(251): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
qatest-php  | #8 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(227): GuzzleHttp\Promise\Promise->invokeWaitFn()
qatest-php  | #9 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
qatest-php  | #10 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
qatest-php  | #11 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(272): GuzzleHttp\Promise\Promise->waitIfPending()
qatest-php  | #12 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(229): GuzzleHttp\Promise\Promise->invokeWaitList()
qatest-php  | #13 /usr/src/app/vendor/guzzlehttp/promises/src/Promise.php(69): GuzzleHttp\Promise\Promise->waitIfPending()
qatest-php  | #14 /usr/src/app/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\Promise\Promise->wait()
qatest-php  | #15 /usr/src/app/vendor/aws/aws-sdk-php/src/ResultPaginator.php(138): Aws\AwsClient->execute(Object(Aws\Command))
qatest-php  | #16 /usr/src/app/vendor/aws/aws-sdk-php/src/functions.php(52): Aws\ResultPaginator->valid()
qatest-php  | #17 /usr/src/app/vendor/aws/aws-sdk-php/src/functions.php(69): Aws\map(Object(Aws\ResultPaginator), Object(Closure))
qatest-php  | #18 [internal function]: Aws\flatmap(Object(Aws\ResultPaginator), Object(Closure))
qatest-php  | #19 /usr/src/app/vendor/humanmade/s3-uploads/inc/class-stream-wrapper.php(695): Generator->valid()
qatest-php  | #20 [internal function]: S3_Uploads\Stream_Wrapper->dir_readdir()
qatest-php  | #21 /usr/src/app/vendor/humanmade/s3-uploads/inc/class-plugin.php(676): scandir('s3://s3-qatest/...')
qatest-php  | #22 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(324): S3_Uploads\Plugin->get_files_for_unique_filename_file_list(NULL, 's3://s3-qatest/...', 'zed1-img_1777.j...')
qatest-php  | #23 /usr/src/app/wordpress/wp-includes/plugin.php(205): WP_Hook->apply_filters(NULL, Array)
qatest-php  | #24 /usr/src/app/wordpress/wp-includes/functions.php(2667): apply_filters('pre_wp_unique_f...', NULL, 's3://s3-qatest/...', 'zed1-img_1777.j...')
qatest-php  | #25 /usr/src/app/wordpress/wp-admin/includes/file.php(984): wp_unique_filename('s3://s3-qatest/...', 'zed1-img_1777.j...', NULL)
qatest-php  | #26 /usr/src/app/wordpress/wp-admin/includes/file.php(1105): _wp_handle_upload(Array, Array, '2024-08-07 09:3...', 'wp_handle_uploa...')
qatest-php  | #27 /usr/src/app/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(1322): wp_handle_upload(Array, Array, '2024-08-07 09:3...')
qatest-php  | #28 /usr/src/app/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(269): WP_REST_Attachments_Controller->upload_from_file(Array, Array, '2024-08-07 09:3...')
qatest-php  | #29 /usr/src/app/wordpress/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php(158): WP_REST_Attachments_Controller->insert_attachment(Object(WP_REST_Request))
qatest-php  | #30 /usr/src/app/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1230): WP_REST_Attachments_Controller->create_item(Object(WP_REST_Request))
qatest-php  | #31 /usr/src/app/wordpress/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wp/v2/media', Array, NULL)
qatest-php  | #32 /usr/src/app/wordpress/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server->dispatch(Object(WP_REST_Request))
qatest-php  | #33 /usr/src/app/wordpress/wp-includes/rest-api.php(420): WP_REST_Server->serve_request('/wp/v2/media')
qatest-php  | #34 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
qatest-php  | #35 /usr/src/app/wordpress/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(false, Array)
qatest-php  | #36 /usr/src/app/wordpress/wp-includes/plugin.php(565): WP_Hook->do_action(Array)
qatest-php  | #37 /usr/src/app/wordpress/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
qatest-php  | #38 /usr/src/app/wordpress/wp-includes/class-wp.php(813): WP->parse_request('')
qatest-php  | #39 /usr/src/app/wordpress/wp-includes/functions.php(1336): WP->main('')
qatest-php  | #40 /usr/src/app/wordpress/wp-blog-header.php(16): wp()
qatest-php  | #41 /usr/src/app/index.php(21): require('/usr/src/app/wo...')
qatest-php  | #42 {main}
qatest-php  |   thrown in /usr/src/app/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 196
qatest-php  | [07-Aug-2024 09:35:43 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 41943040 bytes) in /usr/src/app/vendor/humanmade/s3-uploads/inc/class-plugin.php on line 676

```

- Further testing.
- Tried connecting to S3 from the docker shell - didn't work. Same from v19

```shell
$ composer server ssh
www-data@a7c1f17b35b0:/usr/src/app$ curl "https://altis19.altis.dev/s3-altis19/"
curl: (7) Failed to connect to altis19.altis.dev port 443 after 42 ms: Couldn't connect to server
www-data@a7c1f17b35b0:/usr/src/app$
```

- testing inside `qa-test` v20 gave this
```shell
www-data@08674edaddfe:/usr/src/app$ curl -if 'http://s3:9000/minio/health/live'
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 0
Content-Security-Policy: block-all-mixed-content
Server: MinIO
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 17E97BFE1103A8B1
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Date: Wed, 07 Aug 2024 15:31:03 GMT

www-data@08674edaddfe:/usr/src/app$
```

- testing `qatest` v20 again. FQDN for S3 does not work
```shell
www-data@08674edaddfe:/usr/src/app$ curl "http://s3-qatest.altis.dev:9000/s3-qatest/"
curl: (7) Failed to connect to s3-qatest.altis.dev port 9000 after 4 ms: Couldn't connect to server
```

- but short name does work

```shell
www-data@08674edaddfe:/usr/src/app$ curl "http://s3:9000/s3-qatest/"
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>s3-qatest</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated></ListBucketResult>www-data@08674edaddfe:/usr/src/app$
```

- same problem with qatest. Also, s3-uploads command broken too
```shell
$ composer server cli -- s3-uploads upload-directory tmp uploads
Error: Error executing "PutObject" on "https://s3-qatest.altis.dev/s3-qatest/uploads/zed1-img_1922.jpg"; 
  AWS HTTP error: cURL error 7: Failed to connect to s3-qatest.altis.dev port 443 after 0 ms: 
  Couldn\'t connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3-qatest.altis.dev/s3-qatest/uploads/zed1-img_1922.jpg
```

Acceptance criteria:

- [ ] ...

**Comment by mikelittle** [comment]
Ah, OK. That was my expectation too, but I couldn't figure out where it was picking up the FQDN from. I assumed it had always used the full name and worked somehow before.  
If it might be something an AWS SDK update has done, that gives me a pointer to track this down. Still, odd that it works on a brand-new installation on an old Mac, and continues to work on new installations on linux VMs.

**Comment by roborourke** [comment]
It might be worth tinkering with this code a bit

https://github.com/humanmade/altis-local-server/blob/master/inc/namespace.php#L28-L37

I would try adding some breakpoints with xdebug to see which URL its trying to use. It might arrive at the FQDN as part of some attempts to retry or try different versions of the S3 endpoint.

I can't actually remember why the S3 endpoint is set to the FQDN, I thought it should be the internal container link URL e.g. `s3` or `s3.localhost`. It was a fairly complex piece to get working. Odd that it could be inconsistent like this.

Maybe could factor in docker engine versions? Are they same between Mac and Linux?

@abhishek-kaushik is this happening on all your Altis instances or only some? What about on a clean install?

**Comment by abhishek-kaushik** [comment]
Yes @roborourke I am facing this issue on all of my stacks

**Comment by ferschubert-hm** [comment]
Could not reproduce the error, actions performed:

1. New local server env created
2. `composer create-project altis/skeleton estudo`
3. `composer server start`
4. Added images to the library as superadmin -> ok
5. Added images to a post as author -> ok

Additional detail:
- Altis version: 21
- `composer server status` output:
<img width="1239" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNk5QQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9f3adbfb7d4f8e7030bd460333b4e75b7a595273/image.png" alt="image.png" />

**Comment by ferschubert-hm** [comment]
@abhishek-kaushik could you provide some info on the Altis version and a an output for `composer server status`? Thanks!

**Comment by mikelittle** [comment]
Remarkably, this has disappeared for me. With the same repository still checked out. Whilst there have been many package updates and many cycles of `composer server start/destroy`, I think the most significant change is that I changed my DNS over the holiday break. 
I had previously been using Tailscale which does takes over DNS lookups before passing them on as normal. Note: I used Tailscale for over 18 months before this problem started happening. Over the break, I finally implemented a couple of pi-hole servers and directed both my home network and Tailscale to query the pi-hole servers first. Now the S3 container lookup does not fail.
@abhishek-kaushik Do you have any kind of VPN (standard or mesh), system level ad-blocker, or other thing that may insert itself in the DNS lookup process?

**Comment by joehoyle** [comment]
I think this might have been fixed by #777 / https://github.com/humanmade/altis-dev-tools/issues/845

**Comment by abhishek-kaushik** [comment]
@mikelittle not I am not using any VPN or anything else.

@joehoyle I am still facing the similar issue- I did try to update `local-server` to `21.0.7`

**Comment by rmccue** [comment]
@abhishek-kaushik What do you get with a `curl` to the URL or a `dig` on the domain name?

**Comment by abhishek-kaushik** [comment]
@rmccue , here it is

```
dig https://altis-media.altis.dev

; <<>> DiG 9.10.6 <<>> https://altis-media.altis.dev
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10667
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1280
;; QUESTION SECTION:
;https://altis-media.altis.dev.	IN	A

;; ANSWER SECTION:
https://altis-media.altis.dev. 300 IN	A	127.0.0.1

;; Query time: 16 msec
;; SERVER: 192.168.29.1#53(192.168.29.1)
;; WHEN: Thu Mar 27 10:20:06 IST 2025
;; MSG SIZE  rcvd: 74
```

```
curl -I https://altis-media.altis.dev
HTTP/2 200 
content-security-policy: object-src 'none'; base-uri 'self'
content-type: text/html; charset=UTF-8
date: Thu, 27 Mar 2025 04:49:48 GMT
link: <https://altis-media.altis.dev/wp-json/>; rel="https://api.w.org/"
server: nginx
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```

```
curl -I https://s3-altis-media.altis.dev
HTTP/2 400 
accept-ranges: bytes
content-type: application/xml
date: Thu, 27 Mar 2025 04:58:05 GMT
server: MinIO
vary: Origin
x-amz-bucket-region: us-east-1
content-length: 287
```

```
curl -I https://s3-altis-media.altis.dev:9001
curl: (7) Failed to connect to s3-altis-media.altis.dev port 9001 after 1 ms: Couldn't connect to server
```

**Comment by rmccue** [comment]
OK, looks like that's not a DNS resolution error as it is resolving, but not connecting. The 400 error there is expected (it's a bad request).

@mikelittle Does this look like the same issue? From above it seemed like DNS resolution, but possible it was HTTP problem instead?

**Comment by mikelittle** [comment]
I'm not sure whether this is the same issue. Certainly, the fix Joe mentions is not related because I could intermittently get the same problem with the Tachyon container.

@abhishek-kaushik, is that last test the correct hostname? Should it be altis-media-s3?



Now things are working for me on my stack here is what I get:

- From my host machine (my laptop) the S3 container is not reachable on that port. That is the internal port that only works inside docker. 
You can get the external port from `docker ps`
```
e318ba690835   minio/minio:RELEASE.2021-09-18T18-09-59Z           "/usr/bin/docker-ent…"   8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:32897->9000/tcp, [::]:32897->9000/tcp, 0.0.0.0:32898->9001/tcp, [::]:32898->9001/tcp                                altis-dev-s3
```
Here it is `32898`.
It's also not TLS terminated.

So this works for me from the host:

```shell
$ curl -I http://altis-dev-s3.altis.dev:32898
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2968
Content-Type: text/html; charset=utf-8
Last-Modified: Thu, 27 Mar 2025 14:56:34 GMT
Server: MinIO Console
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Thu, 27 Mar 2025 14:56:34 GMT
Connection: close
```

Inside the PHP container, that doesn't work. It shouldn't: the FQDN resolves to 127.0.0.1 which is the PHP container. And also inside the containers it is port 9001.
So the FQDN doesn't work, but the short name without the TLD does work:

```shell
www-data@1913424552d2:/usr/src/app$ curl -I http://altis-dev-s3.altis.dev:9001
curl: (7) Failed to connect to altis-dev-s3.altis.dev port 9001 after 120 ms: Couldn't connect to server

www-data@1913424552d2:/usr/src/app$ curl -I http://altis-dev-s3:9001
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2968
Content-Type: text/html; charset=utf-8
Last-Modified: Thu, 27 Mar 2025 15:01:10 GMT
Server: MinIO Console
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Thu, 27 Mar 2025 15:01:10 GMT
Connection: close
```

**Comment by abhishek-kaushik** [comment]
@mikelittle @rmccue, Yes I am getting `200 ok` for `curl -I http://altis-media-s3.altis.dev:32777`

```
curl -I http://altis-media-s3.altis.dev:32777
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2968
Content-Type: text/html; charset=utf-8
Last-Modified: Fri, 28 Mar 2025 06:53:39 GMT
Server: MinIO Console
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Fri, 28 Mar 2025 06:53:39 GMT
Connection: close
```

and 
```
www-data@25ff2f0c5eda:/usr/src/app$ curl -I http://altis-media-s3:9001
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 2968
Content-Type: text/html; charset=utf-8
Last-Modified: Fri, 28 Mar 2025 06:57:30 GMT
Server: MinIO Console
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
Date: Fri, 28 Mar 2025 06:57:30 GMT
Connection: close
```

I was trying `https://s3-altis-media.altis.dev` because

```
www-data@25ff2f0c5eda:/usr/src/app$ echo $S3_UPLOADS_BUCKET_URL
https://s3-altis-media.altis.dev
```

FWIW
```
www-data@25ff2f0c5eda:/usr/src/app$ curl -I https://altis-media-s3:9001
curl: (35) OpenSSL/3.0.15: error:0A00010B:SSL routines::wrong version number
```
```
curl -I https://s3-altis-media.altis.dev:32777
curl: (35) LibreSSL/3.3.6: error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version
```

**Comment by abhishek-kaushik** [comment]
for what it's worth

```
cs cli -- shell --url=https://<REDACTED>.altis.dev/sg
Psy Shell v0.12.8 (PHP 8.1.31 — cli) by Justin Hileman
> wp_remote_get('https://<REDACTED>.altis.dev/sg/wealth/insights/test-wealth-insights/');
= WP_Error {#15654
    +errors: [
      "http_request_failed" => [
        "cURL error 7: Failed to connect to <REDACTED>.altis.dev port 443 after 24 ms: Couldn't connect to server",
      ],
    ],
    +error_data: [],
  }
```
